apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api
  labels:
    app: api
spec:
  serviceName: api
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          imagePullPolicy: Always
        #   image: {{ .Values.backend.image }}
          image: gwin300/backend_api
---
apiVersion: v1
kind: Service
metadata:
  name: api
  annotations: 
    alb.ingress.kubernetes.io/healthcheck-port: '9999'
    alb.ingress.kubernetes.io/healthcheck-path: /time
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: api
